alias g='git'
alias v='vim'
alias d='git d'
alias dw='git dw'
alias D='git dd'
alias c='git c'
alias cw='git cw'
alias C='git cc'
alias s='git status --short --branch'
alias t='tig'
alias p='popd'
alias gl='g l'
alias gg='g g'
alias :q='exit'
alias :z="v $DOTFILES_PATH/home/.zshrc"
alias :zl="v ~/.zshrc_local"
alias :zz=". $DOTFILES_PATH/home/.zshrc"
alias :b="v $DOTFILES_PATH/home/.bashrc"
alias :bb=". $DOTFILES_PATH/home/.bashrc"
alias :f="v $DOTFILES_PATH/home/.config/fish/config.fish"
alias :ff=". $DOTFILES_PATH/home/.config/fish/config.fish"
alias :fl="v $HOME/fish_local_config.fish"
alias :fu="v $DOTFILES_PATH/home/.config/fish/functions/fish_user_key_bindings.fish"
alias :fp="v $DOTFILES_PATH/home/.config/fish/functions/fish_prompt.fish"
alias :a="v $DOTFILES_PATH/aliases.sh"
alias :v="v $DOTFILES_PATH/home/.vimrc"
alias :gc="v $DOTFILES_PATH/home/.gitconfig"
alias :gcl="v ~/.gitconfig_local"
alias :sc='v ~/.ssh/config'
alias :d='homeshick cd dotfiles'
alias :t="v $DOTFILES_PATH/home/.tigrc"
alias :g='cd ~/github'
alias :rg='cd ~/repo/github.com'
alias ts='tig status'
alias fo='git fetch origin'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias ut='bundle exec ruby -Itest'
alias dbe='docker-compose exec spring bin/spring'
alias dbi='dcm run --rm spring bundle install'
alias drun='docker-compose exec spring'
alias docker-su='docker run -it --rm --privileged --pid=host justincormack/nsenter1'
alias git-new-workdir="$HOMEBREW_PATH/share/git-core/contrib/workdir/git-new-workdir"
alias ws='python -m SimpleHTTPServer'
