#!/usr/bin/env perl

use strict;
use warnings;

use File::Spec;

my $homedir = $ENV{'HOME'} || die "Environment variable HOME isn't set";
my $targetdir = File::Spec->catfile($homedir, ".byobu");
foreach (qw/.tmux.conf/) {
    my $f = File::Spec->catfile($targetdir, $_);
    my $t = File::Spec->abs2rel(File::Spec->rel2abs($_), $targetdir);
    print "Creating '$f'";
    if (-e $f) {
        print ": already exists";
    } else {
        symlink($t, $f) || print ": cannot create"
    }
    print "\n";
}
