#!/usr/bin/env bash

./mksymlinks

pushd .vim/bundle
rm -fr vundle
git clone git://github.com/gmarik/vundle.git
popd

vim -c ":BundleInstall"
vim -c ":BundleClean"

echo "Now you need build vimproc in .vim/bundle/vimproc"
