cask_args appdir: '/Applications'

brew 'awscli'
brew 'anyenv'
brew 'dive'
brew 'fzf'
brew 'git'
brew 'github/gh/gh'
brew 'heroku'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'mutagen'
brew 'ncdu'
brew 'pulumi'
brew 'zplug'
brew 'zsh'

cask '1password-beta'
cask 'avast-security'
cask 'appcleaner'
cask 'bartender'
cask 'cinch'
cask 'dash'
cask 'docker'
cask 'dischord'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'google-photos-backup-and-sync'
cask 'gswitch'
cask 'haptickey'
cask 'homebrew/cask-versions/visual-studio-code-insiders'
cask 'intel-power-gadget'
cask 'invisor-lite'
cask 'istat-menus'
cask 'iterm2'
cask 'karabiner-elements'
cask 'keybase'
cask 'keyboardcleantool'
cask 'kite'
cask 'musescore'
cask 'music-manager'
cask 'notion'
cask 'spectacle'
cask 'tableplus'
cask 'visual-studio-code-insiders'
cask 'youtube-to-mp3'

mas 'Amphetamine', id: 937984704
mas 'GIPHY Capture', id: 668208984
mas 'Kindle', id: 405399194
mas 'LINE', id: 539883307
mas 'Slack', id: 803453959
mas 'Twitter', id: 1482454543
mas 'Xcode', id: 497799835
