#!/bin/bash -eux

echo y | anyenv install --init

# latest zsh is installed with homebrew, so setup after install.

rm -rf ~/.zinit/bin
mkdir -p ~/.zinit
git clone https://github.com/zdharma/zinit.git ~/.zinit/bin

/usr/local/bin/zsh -ic 'echo Zsh initial run succeeded.'
sudo chsh -s /usr/local/bin/zsh $USER
